[project]
name = "DIFI"
version = "v1.0.0"
authors = [
  { name="Li-Yin Young", email="author@example.com" },
]
description = "The python module for DIFI-7"
readme = "README.md"
#requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy",
    "geomaglib @ git+https://github.com/CIRES-Geomagnetism/geomaglib.git@v0.1.3"  # Git dependency
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://geomag.colorado.edu/difi-7"
