[project]
name = "difi"
version = "v1.1.0"
authors = [
  { name="Li-Yin Young", email="liyin.young@noaa.gov" },
]
description = "The python module for DIFI-7"
readme = "README.md"
#requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy",
    "geomaglib==0.4.4"
    #"geomaglib @ git+https://github.com/CIRES-Geomagnetism/geomaglib.git@main"  # Git dependency
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/CIRES-Geomagnetism/DIFI"
