name: Release the wheels to Github Release

on:
  push:
    branches: ['py_wheel']


jobs:
  build_wheels:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build 

      - name: Build package
        run: python -m build --wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-3.13
          path: dist/

  test_artifacts:
    runs-on: windows-latest
    needs: build_wheels

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pydifi-7.2.0-py3-none-any.whl

      - name: Test installation
        shell: bash
        run: |
          python -c "import DIFI as difi; print(difi.__version__)"


  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_wheels, test_artifacts]

    steps:

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
          draft: true
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This release includes the following wheels:
            ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}