name: DIFI Pull Request CI pipeline

on:
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python_version: ['3.9', '3.10', '3.11', '3.12', '3.13']

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
              python-version: ${{ matrix.python_version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -e .

        - name: System Test
          run: |
            python tests/validate_CM6.py

